package ORM_DB;
// Generated 01-Jul-2018 13:16:39 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Claims generated by hbm2java
 */
@Entity
@Table(name="claims"
    ,catalog="dca"
)
public class Claims  implements java.io.Serializable {


     private int id;
     private String memId;
     private Date date;
     private String rationale;
     private String status;
     private float amount;

    public Claims() {
    }

    public Claims(int id, String memId, Date date, String rationale, String status, float amount) {
       this.id = id;
       this.memId = memId;
       this.date = date;
       this.rationale = rationale;
       this.status = status;
       this.amount = amount;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="mem_id", nullable=false, length=20)
    public String getMemId() {
        return this.memId;
    }
    
    public void setMemId(String memId) {
        this.memId = memId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date", nullable=false, length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="rationale", nullable=false, length=16777215)
    public String getRationale() {
        return this.rationale;
    }
    
    public void setRationale(String rationale) {
        this.rationale = rationale;
    }

    
    @Column(name="status", nullable=false, length=10)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="amount", nullable=false, precision=12, scale=0)
    public float getAmount() {
        return this.amount;
    }
    
    public void setAmount(float amount) {
        this.amount = amount;
    }




}


