package ORM_DB;
// Generated 01-Jul-2018 13:16:39 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Members generated by hbm2java
 */
@Entity
@Table(name="members"
    ,catalog="dca"
)
public class Members  implements java.io.Serializable {


     private String id;
     private String name;
     private String address;
     private Date dob;
     private Date dor;
     private String status;
     private float balance;

    public Members() {
    }

	
    public Members(String id, String status, float balance) {
        this.id = id;
        this.status = status;
        this.balance = balance;
    }
    public Members(String id, String name, String address, Date dob, Date dor, String status, float balance) {
       this.id = id;
       this.name = name;
       this.address = address;
       this.dob = dob;
       this.dor = dor;
       this.status = status;
       this.balance = balance;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false, length=20)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    @Column(name="name", length=40)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="address", length=16777215)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dob", length=10)
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dor", length=10)
    public Date getDor() {
        return this.dor;
    }
    
    public void setDor(Date dor) {
        this.dor = dor;
    }

    
    @Column(name="status", nullable=false, length=10)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="balance", nullable=false, precision=12, scale=0)
    public float getBalance() {
        return this.balance;
    }
    
    public void setBalance(float balance) {
        this.balance = balance;
    }




}


