package ORM_DB;
// Generated 01-Jul-2018 13:16:39 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Payments generated by hbm2java
 */
@Entity
@Table(name="payments"
    ,catalog="dca"
)
public class Payments  implements java.io.Serializable {


     private int id;
     private String memId;
     private String typeOfPayment;
     private float amount;
     private Date date;
     private Date time;

    public Payments() {
    }

    public Payments(int id, String memId, String typeOfPayment, float amount, Date date, Date time) {
       this.id = id;
       this.memId = memId;
       this.typeOfPayment = typeOfPayment;
       this.amount = amount;
       this.date = date;
       this.time = time;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="mem_id", nullable=false, length=20)
    public String getMemId() {
        return this.memId;
    }
    
    public void setMemId(String memId) {
        this.memId = memId;
    }

    
    @Column(name="type_of_payment", nullable=false, length=10)
    public String getTypeOfPayment() {
        return this.typeOfPayment;
    }
    
    public void setTypeOfPayment(String typeOfPayment) {
        this.typeOfPayment = typeOfPayment;
    }

    
    @Column(name="amount", nullable=false, precision=12, scale=0)
    public float getAmount() {
        return this.amount;
    }
    
    public void setAmount(float amount) {
        this.amount = amount;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date", nullable=false, length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="time", nullable=false, length=8)
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }




}


